import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import '@/styles/globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import  { Toaster } from 'react-hot-toast';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <main className='md:max-w-7xl mx-auto  bg-[#FCFCFC] p-4 h-full'>
          <Navbar />
          {children}
          <Footer />
          <Toaster
            position="top-center"
            reverseOrder={false}
          />
        </main>
      </body>
    </html>
  );
}
